server:
  port: 8080

spring:
  jpa:
#    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/user_registration
    username: postgres
    password: maria@12yarmole
    driverClassName: org.postgresql.Driver
#spring:
#  jpa:
##    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/user_registration
#    username: postgres
#    password: maria@12yarmole
#    driverClassName: org.postgresql.Driver

#
#  spring:
#    datasource:
#      url: jdbc:postgresql://localhost:5432/user_registration
#        username: postgres
#          password: maria@12yarmole
#            driver-class-name: org.postgresql.Driver
#  spring.jpa:
#    show-sql: true
#      hibernate:
#        ddl-auto: update